### ISSUE TITLE
Form fields?

### ISSUE THREAD

**Issue by seenickcode** [aqwert/flutter_platform_widgets#1]
Hey there, excellent work with this. I'm writing a Flutter app now and it's just what I need.

I was wondering if you've considered implementing iOS style form fields or if that's too complex?  I ask because the main challenge I have is how iOS treats validation, where there's real built in way to show validation error messages next to the iOS form field, one usually shows a UIAlert for any errors.

Any thoughts on that?

**Comment by aqwert** [comment]
I am not that familiar with how iOS forms work but the complexity does creep in when needing to validate more than 1 field and then display an error either in-line or as a result of a submit button tap (dialog). This logic has little to do with the widget itself and is more around the way the Form class and Controllers are used. see : https://flutter.rocks/2017/10/17/validating-forms-in-flutter/

It is possible to display the PlatformAlertDialog once it is validated, but anything more than that would be a lot of work.

Also this library is really just a wrapper of Flutter widgets (for now at least) and there does not seen to be a CupertinoTextFormField.

**Comment by seenickcode** [comment]
Right.  Well in my experience implementing forms on iOS, it's basically up
to you how and when you want to show validation errors. Typically this is
done by showing a popup alert dialog when submitting the form.  The current
implementation of the Flutter Form class accommodates this but in terms of
how the text fields behave, it seems that in order to get an iOS feel, I
have to style each control manually to remove the real estate taken up by
the text field label as well as area taken up by any validation message.

Anyway, those are just some thoughts. Thanks for your reply. Cheers.
