### ISSUE TITLE
Support gradient for Cupertino app bar

### ISSUE THREAD

**Issue by Musasshi90** [aqwert/flutter_platform_widgets#100]
Hello, is it possible that your Cupertino app bar can add the gradient feature? Currently only android app bar which has flexibleSpace can support the gradient, but Cupertino app bar don't support the gradient.

**Comment by aqwert** [comment]
This library is just a wrapper to the underlying material and cupertino widgets. If it is not supported on those this package also won't support it.

I suggest that since this quite a custom design you will need to specifically build it for your project.
