### ISSUE TITLE
iOS APP: There are multiple heroes that share the same tag within a subtree.

### ISSUE THREAD

**Issue by sabarnett** [aqwert/flutter_platform_widgets#101]
Ok, I'm a bit of a rookie when it comes to Flutter and this one is way above my skill level. I converted my app to use the flutter_platform_widgets package and everything works fine in the android emulator. In the ios emulator, I get the error below. 

My app runs a questionnaire then displays a screen with two bottom tabs. Clicking the back button without clicking a tab is fine. However, if I click one of the tabs to change the page displayed then click back, I get this error and the top nav bar disappears from the page I go back to.

      ════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
      The following assertion was thrown during a scheduler callback:
      There are multiple heroes that share the same tag within a subtree.
     
     Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
     In this case, multiple heroes had the following tag: Default Hero tag for Cupertino navigation bars with navigator NavigatorState#4e83b(tickers: tracking 2 tickers)
     Here is the subtree for one of the offending heroes:
     # Hero(tag: Default Hero tag for Cupertino navigation bars with navigator NavigatorState#4e83b(tickers: tracking 2 tickers), state: _HeroState#43e9d)
     # └SizedBox(renderObject: RenderConstrainedBox#8d23c relayoutBoundary=up1 NEEDS-PAINT)
     #  └Offstage(offstage: false, renderObject: RenderOffstage#0fd57 relayoutBoundary=up2 NEEDS-PAINT)
     #   └TickerMode(mode: enabled)
     #    └KeyedSubtree-[GlobalKey#0ab20]
     #     └_TransitionableNavigationBar-[GlobalKey#223ce Navigation bar render box]
     #      └ClipRect(renderObject: RenderClipRect#1ffa9 relayoutBoundary=up3 NEEDS-PAINT)
     #       └BackdropFilter(renderObject: RenderBackdropFilter#0bb49 relayoutBoundary=up4 NEEDS-PAINT)
     #        └DecoratedBox(bg: BoxDecoration(color: Color(0xccf8f8f8), border: Border(bottom: BorderSide(Color(0x4c000000), 0.0, BorderStyle.solid))), dependencies: [Directionality, MediaQuery, _LocalizationsScope-[GlobalKey#ed332]], renderObject: RenderDecoratedBox#66e5c relayoutBoundary=up5 NEEDS-PAINT)
     #         └AnnotatedRegion<SystemUiOverlayStyle>(renderObject: RenderAnnotatedRegion<SystemUiOverlayStyle>#0295f relayoutBoundary=up6 NEEDS-PAINT)
     #          └DefaultTextStyle(inherit: false, color: Color(0xff000000), family: .SF Pro Text, size: 17.0, letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
     #           └_PersistentNavigationBar(dependencies: [MediaQuery, _InheritedCupertinoTheme])
     #            └SizedBox(height: 88.0, renderObject: RenderConstrainedBox#88e11 relayoutBoundary=up7 NEEDS-PAINT)
     #             └SafeArea(avoid left padding, avoid top padding, avoid right padding, avoid bottom padding, dependencies: [MediaQuery])
     #              └Padding(padding: EdgeInsets(0.0, 44.0, 0.0, 0.0), dependencies: [Directionality], renderObject: RenderPadding#2424f NEEDS-PAINT)
     #               └MediaQuery(MediaQueryData(size: Size(414.0, 896.0), devicePixelRatio: 3.0, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 0.0, 0.0, 84.0), viewPadding: EdgeInsets.zero, viewInsets: EdgeInsets.zero, physicalDepth: 1.7976931348623157e+308, alwaysUse24HourFormat: false, accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false))
     #                └NavigationToolbar(dependencies: [Directionality])
     #                 └CustomMultiChildLayout(renderObject: RenderCustomMultiChildLayoutBox#1b9e7 NEEDS-PAINT)
     #                  ├LayoutId-[<_ToolbarSlot.leading>](id: _ToolbarSlot.leading)
     #                  │└CupertinoNavigationBarBackButton(dependencies: [_InheritedCupertinoTheme, _ModalScopeStatus])
     #                  │ └CupertinoButton(dependencies: [_InheritedCupertinoTheme, TickerMode], state: _CupertinoButtonState#6811c(ticker inactive))
     #                  │  └GestureDetector(startBehavior: start)
     #                  │   └RawGestureDetector(state: RawGestureDetectorState#9c7f8(gestures: [tap], behavior: opaque))
     #                  │    └_GestureSemantics(renderObject: RenderSemanticsGestureHandler#13b4c relayoutBoundary=up1)
     #                  │     └Listener
     #                  │      └_PointerListener(listeners: [down], behavior: opaque, renderObject: RenderPointerListener#bc297 relayoutBoundary=up2)
     #                  │       └Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#2099e relayoutBoundary=up3)
     #                  │        └ConstrainedBox(BoxConstraints(44.0<=w<=Infinity, 44.0<=h<=Infinity), renderObject: RenderConstrainedBox#4893c relayoutBoundary=up4)
     #                  │         └FadeTransition(opacity: AnimationController#bec05(⏮ 0.000; paused)➩CurveTween(curve: _DecelerateCurve)➩0.0➩Tween<double>(1.0 → 0.1)➩1.0, renderObject: RenderAnimatedOpacity#f509e relayoutBoundary=up5)
     #                  │          └DecoratedBox(bg: BoxDecoration(borderRadius: BorderRadius.circular(8.0)), dependencies: [Directionality, MediaQuery, _LocalizationsScope-[GlobalKey#ed332]], renderObject: RenderDecoratedBox#de364 relayoutBoundary=up6)
     #                  │           └Padding(padding: EdgeInsets.zero, dependencies: [Directionality], renderObject: RenderPadding#a0f0d relayoutBoundary=up7)
     #                  │            └Center(alignment: center, widthFactor: 1.0, heightFactor: 1.0, dependencies: [Directionality], renderObject: RenderPositionedBox#444ae relayoutBoundary=up8)
     #                  │             └DefaultTextStyle(inherit: false, color: Color(0xff007aff), family: .SF Pro Text, size: 17.0, letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
     #                  │              └IconTheme(IconThemeData#33904(color: Color(0xff007aff)))
     #                  │               └Semantics(container: true, properties: SemanticsProperties, label: "Back", value: null, hint: null, hintOverrides: null, dependencies: [Directionality], renderObject: RenderSemanticsAnnotations#d3fc6 relayoutBoundary=up9)
     #                  │                └DefaultTextStyle(inherit: false, color: Color(0xff007aff), family: .SF Pro Text, size: 17.0, letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
     #                  │                 └ConstrainedBox(BoxConstraints(50.0<=w<=Infinity, 0.0<=h<=Infinity), renderObject: RenderConstrainedBox#4806a relayoutBoundary=up10)
     #                  │                  └Row(direction: horizontal, mainAxisAlignment: start, mainAxisSize: min, crossAxisAlignment: center, dependencies: [Directionality], renderObject: RenderFlex#f4b9b relayoutBoundary=up11)
     #                  │                   ├Padding(padding: EdgeInsetsDirectional(8.0, 0.0, 0.0, 0.0), dependencies: [Directionality], renderObject: RenderPadding#c596a relayoutBoundary=up12)
     #                  │                   ├KeyedSubtree-[GlobalKey#5636b Back chevron]
     #                  │                   │└_BackChevron(dependencies: [Directionality, DefaultTextStyle])
     #                  │                   │ └Text(null,
     #                  │                   │  │╞═╦══ textSpan ═══
     #                  │                   │  │  ║ TextSpan:
     #                  │                   │  │  ║   inherit: false
     #                  │                   │  │  ║   color: Color(0xff007aff)
     #                  │                   │  │  ║   family: packages/cupertino_icons/CupertinoIcons
     #                  │                   │  │  ║   size: 34.0
     #                  │                   │  │  ║   ""
     #                  │                   │  │, dependencies: [MediaQuery, DefaultTextStyle])
     #                  │                   │  └RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "", dependencies: [Directionality, _LocalizationsScope-[GlobalKey#ed332]], renderObject: RenderParagraph#477a5 relayoutBoundary=up12)
     #                  │                   ├Padding(padding: EdgeInsetsDirectional(6.0, 0.0, 0.0, 0.0), dependencies: [Directionality], renderObject: RenderPadding#92152 relayoutBoundary=up12)
     #                  │                   └Flexible(flex: 1)
     #                  │                    └KeyedSubtree-[GlobalKey#b8151 Back label]
     #                  │                     └_BackLabel
     #                  │                      └ValueListenableBuilder<String>(state: _ValueListenableBuilderState<String>#72ddc)
     #                  │                       └SizedBox.shrink(renderObject: RenderConstrainedBox#0f080 relayoutBoundary=up12)
     #                  └LayoutId-[<_ToolbarSlot.middle>](id: _ToolbarSlot.middle)
     #                   └DefaultTextStyle(inherit: false, color: Color(0xff000000), family: .SF Pro Text, size: 17.0, weight: 600, letterSpacing: -0.4, softWrap: wrapping at box width, overflow: clip)
     #                    └Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#533da relayoutBoundary=up1 NEEDS-PAINT)
     #                     └KeyedSubtree-[GlobalKey#5727a Middle]
     #                      └Text("Role Profile", dependencies: [MediaQuery, DefaultTextStyle])
     #                       └RichText(softWrap: wrapping at box width, maxLines: unlimited, text: "Role Profile", dependencies: [Directionality, _LocalizationsScope-[GlobalKey#ed332]], renderObject: RenderParagraph#a1a17 relayoutBoundary=up2 NEEDS-PAINT)
    
     When the exception was thrown, this was the stack: 
     #0      Hero._allHeroesFor.inviteHero.<anonymous closure> (package:flutter/src/widgets/heroes.dart:265:11)
     #1      Hero._allHeroesFor.inviteHero (package:flutter/src/widgets/heroes.dart:275:8)
     #2      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:294:21)
     #3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3990:14)
     #4      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:307:15)
     ...
         ═══════

When I display the results page (the one with the two tabs), I do so with this code:

    Navigator.of(context).pushNamed(ResultScreen.route,
        arguments: {
              'questionnaire': _questionnaire,
              'analysis': _analysis
          }).then((value) {
            _resetQuiz();
      });

      
This page I am coming from is defined as:

    @override
    Widget build(BuildContext context) {
      return PlatformScaffold(
          iosContentBottomPadding: true,
          iosContentPadding: true,
          appBar: PlatformAppBar(
            title: Text('More about you...'),
            trailingActions: [
            PlatformIconButton(
              iosIcon: Icon(CupertinoIcons.refresh, size:28),
                androidIcon: Icon(Icons.refresh),
                onPressed: _shouldResteQuiz,
              ),
            ],
          ),
       
          body: QuizQuestion(_currentQuestion, _answerQuestion, _questionnaire.count)
       );
      }

  
The target page is defined as:
  
      void _selectPage(int index){
      setState(() {
        _pageTitle = _pages[index]['title'];
        _selectedPage = index;
      });
    }

    @override
    Widget build(BuildContext context) {

      return PlatformScaffold(
        iosContentPadding: true,
        iosContentBottomPadding: true,
        appBar: PlatformAppBar(
          title: Text(_pageTitle),
        ),

      body: _pages[_selectedPage]['page'],

      bottomNavBar: PlatformNavBar(
        itemChanged: _selectPage,
        currentIndex: _selectedPage,
        items: [
          BottomNavigationBarItem(icon: Icon(Icons.receipt), title: Text(_pages[0]['title'])),
          BottomNavigationBarItem(icon: Icon(Icons.question_answer), title: Text(_pages[1]['title'])),
        ],
      ),
    );

I'm closing the page with the back button in the nav bar. 

Happy to be told it's my junk code - just need some pointers - I've been at this for a while and an stuck. 

If you want the full source for the project it's at [QuizApp](http://www.sabarnett.co.uk/files/QuizApp.zip)

The calling screen is questionnaireScreen.dart and the target is resultScreen.dart.

Please feel free to tell me to go away!

**Comment by aqwert** [comment]
Had a look at there is an issue in flutter about it: https://github.com/flutter/flutter/issues/22192

You can fix it by adding the following to the `resultScreen.dart` class

```
@override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      iosContentPadding: true,
      iosContentBottomPadding: true,
      appBar: PlatformAppBar(
        title: Text(_pageTitle),
        ios: (context) =>
            CupertinoNavigationBarData(transitionBetweenRoutes: false),
      ),
      body: _pages[_selectedPage]['page'],
      bottomNavBar: PlatformNavBar(
        itemChanged: _selectPage,
        currentIndex: _selectedPage,
        items: [
          BottomNavigationBarItem(
              icon: Icon(Icons.receipt), title: Text(_pages[0]['title'])),
          BottomNavigationBarItem(
              icon: Icon(Icons.question_answer),
              title: Text(_pages[1]['title'])),
        ],
      ),
    );
  }```

Notice the addition of 
```
ios: (context) =>
            CupertinoNavigationBarData(transitionBetweenRoutes: false),
```

**Comment by sabarnett** [comment]
Thank you so much for looking at this, I very much appreciate you spending time on it for me. I’ve added the transition and all is working again.

**Comment by SalimKayJR** [comment]
works like a charm
