### ISSUE TITLE
I think this is a typo mistake 

### ISSUE THREAD

**Issue by salah-yousef** [aqwert/flutter_platform_widgets#102]
Hi there i was trying to use this package and while reading the docs I found this type syntax ...

.
.
.

<img width="1440" alt="Screen Shot 2019-12-11 at 11 11 07" src="https://user-images.githubusercontent.com/17572461/70603607-f8a2f780-1c07-11ea-8837-c61a769fb015.png">

**Comment by aqwert** [comment]
Version 0.30.1 is released. https://pub.dev/packages/flutter_platform_widgets/versions/0.30.1 which addresses this

**Comment by salah-yousef** [comment]
No the same syntax error is still exits .

**Comment by salah-yousef** [comment]
check the parentheses .

**Comment by salah-yousef** [comment]
`return PlatformAppBar(
    title: new Text('Platform Widgets'),
    leading: PlatformIconButton()),
    trailingActions: <Widget>[
      PlatformIconButton(),
    ],
  );`

**Comment by salah-yousef** [comment]
should be `return PlatformAppBar(
    title: new Text('Platform Widgets'),
    leading: PlatformIconButton(),
    trailingActions: <Widget>[
      PlatformIconButton(),
    ],
  );`

**Comment by aqwert** [comment]
Thanks. I have updated the master branch. It will get updated to pub.dev when another release is made
