### ISSUE TITLE
The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'

### ISSUE THREAD

**Issue by EricBichara** [aqwert/flutter_platform_widgets#103]
Getting the following error message on the latest stable version of flutter (v1.12.13+hotfix.5)

> Compiler message:
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:229:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
>  - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
>       final obstruct = navigationBar.fullObstruction == null ||
>                                      ^^^^^^^^^^^^^^^
> ../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:230:25: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
>  - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
>           navigationBar.fullObstruction;
> 

Used a clean project just switching out the to use a PlatformApp

```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return PlatformApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
```

**Comment by aqwert** [comment]
I am in the process of getting Stable to v1.12.13+hotfix.5. In the meantime use https://pub.dev/packages/flutter_platform_widgets/versions/0.20.3-beta.1

**Comment by aqwert** [comment]
Version 0.30.1 is released. https://pub.dev/packages/flutter_platform_widgets/versions/0.30.1 which addresses this
