### ISSUE TITLE
How is using this any different than the default behavior of flutter?

### ISSUE THREAD

**Issue by mingsai** [aqwert/flutter_platform_widgets#105]
I'm just not clear on how this is different than what I achieve by using the default flutter widgets which then recompose themselves as either android or ios widgets. I know that in some cases I may want to compose completely different UI or at times different behaviors for the varying platforms. Also, how will this impact projects that support one of the desktop modes (macos, windows, linux) or the web? 

Thanks in advance for the clarification.

**Comment by aqwert** [comment]
Flutter provides either a material themed library or a cupertino themed library which a developer has to make the choice on what widget to use. There are only a couple of widgets that are adaptive to the target platform but the rest don't render that way..

If you want pretty much the same layout and pages between your Android material app and your Cupertino iOS app then this library may help reduce the amount of conditional logic in your code to display the correct platform themed widget,

As for Web and desktop, currently if you target android, web, windows or linux it will use the material theme and iOS or macos it will use the cupertino theme.

If your want to build a custom themed app that is the same look between platforms then this library is not the best choice
