### ISSUE TITLE
SliverAppbar creating issue with PlatformScaffold and PlatformApp

### ISSUE THREAD

**Issue by shock-wave007** [aqwert/flutter_platform_widgets#108]
No MaterialLocalizations found - MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor

do you have any solution for it.
i try platfromWidgit(android:(_)=>sliverappbar,
ios:(_)=>cupertinosliverappbar)

didn't solve my problem 

platform IOS

everything is fine with android

**Comment by aqwert** [comment]
Could you paste the full code of the page that causes the error. If you search for this issue you will see references to displaying a dialog but you may be something else. This package is just wrappers to the underlying flutter widgets so you would get this issue if you also used the flutter widgets for your platform
