### ISSUE TITLE
Drawer for ios

### ISSUE THREAD

**Issue by mallardexpress** [aqwert/flutter_platform_widgets#109]
Would be awesome to have the ability to display a Drawer on iOS.

I can achieve this using a MaterialApp rather than a PlatformApp, and everything below the App level is the Platform version - PlatformScaffold, etc...  However, this means I can not use a Cupertino Theme and a Drawer at the same time.

I see elsewhere that the iOS UX guideline for a side drawer is for it to appear on the right rather than the left. So the solution would require adding an endDrawer: property to iOS properties for MaterialApp. 

I am not sure how this might work behind the scenes, as the Drawer seems to require some information created by MaterialApp. Does anyone have any ideas?

**Comment by aqwert** [comment]
The underlying Cupertino widgets used are either `CupertinoTabScaffold` or `CupertinoPageScaffold`. Neither of these have a drawer option so therefore `PlatformScaffold` does not have that either.

Have not tried it but you could use Material Scaffold directly and use Cupertino app bar.

Alternatively raise an issue with flutter (https://github.com/flutter/flutter/issues) to get it added to the Cupertino widgets

**Comment by mallardexpress** [comment]
Thanks, I solved this by wrapping it in a Scaffold. For anyone who is interested as follows:

return Scaffold(
          endDrawer: Theme.of(context).platform == TargetPlatform.iOS
              ? _buildDrawer(model)
              : null,
          drawer: Theme.of(context).platform == TargetPlatform.android
              ? _buildDrawer(model)
              : null,
          // Builder gets context from within Scaffold, otherwise it would
          // be from above it, which would not include drawer: or endDrawer:
          body: Builder(builder: (ctx) {
            return PlatformScaffold(
                appBar: _appBar(ctx), body: _layoutPage(context, model));
          }));
