### ISSUE TITLE
The thumbColor in CupertinoSliderData is wrongly defined

### ISSUE THREAD

**Issue by mtorpvret** [aqwert/flutter_platform_widgets#110]
Hi,
It's not possible to set the thumbColor of a PlatformSlider for iOS since the thumbColor is defined as CupertinoColors.
https://github.com/aqwert/flutter_platform_widgets/blob/c04d6852d9858392f15eb6ff1b4618cf5d784852/lib/src/platform_slider.dart#L91

I believe it should be a regular Color, just like the default value is?
https://github.com/aqwert/flutter_platform_widgets/blob/c04d6852d9858392f15eb6ff1b4618cf5d784852/lib/src/platform_slider.dart#L167

**Comment by aqwert** [comment]
I looked at the source and indeed the Cupertino widget uses Color. Will get this fixed

**Comment by aqwert** [comment]
I have published v 0.31.0. Can you check if this resolves your issue.

**Comment by mtorpvret** [comment]
Yes thank you, this works well now!
