### ISSUE TITLE
PlatformText should inherit textTheme from PlatformApp

### ISSUE THREAD

**Issue by tomarra** [aqwert/flutter_platform_widgets#111]
In an attempt to make the PlatformText widget a bit more useful it would be good to have it automatically inherit the textTheme from the PlatformApp. Right now to do this you have to set the style property of the PlatformText individually. On top of that you have to specifically see what platform is being used and call the right theme data (Material or Cupertino). This could be abstracted out to the PlatformText widget so setting the theme at the PlatformApp level actually cascades down.

**Comment by aqwert** [comment]
The PlatformText widget just creates a normal flutter Text widget with the text string upper cased for Android. Everything else should work as if you used `Text` directly. Anything more than that I would feel becomes too opinionated and deviates from the purpose of this project.

**Comment by aqwert** [comment]
Can you check with the latest version as I have fixed issues around theming and properties

**Comment by fredgrott** [comment]
I might get to that as I want to re-enable the google-fonts plugin in my modified example and that has one of its best practices of using the textTheme to load the font via http
