### ISSUE TITLE
PlatformTextField text color is always black 

### ISSUE THREAD

**Issue by MitchTrubisky** [aqwert/flutter_platform_widgets#113]
When no style is provided, CupertinoTextField's text color is black when in light mode and white when in dark mode. PlatformTextField should probably mimic this behavior.

**Comment by aqwert** [comment]
Looking at the source from flutter is that they changed that it does not use a default (static) style. I will match this which will fix this issue

**Comment by aqwert** [comment]
I have published v 0.31.0. Can you check if this resolves your issue.
