### ISSUE TITLE
Text inside of a PlatformScaffold on iOS uses the material style

### ISSUE THREAD

**Issue by MitchTrubisky** [aqwert/flutter_platform_widgets#114]
This seems to be due to wrapping everything with a Material widget here:
https://github.com/aqwert/flutter_platform_widgets/blob/c04d6852d9858392f15eb6ff1b4618cf5d784852/lib/src/platform_scaffold.dart#L205-L215

Out of curiosity, which widgets are still material on iOS?

**Comment by aqwert** [comment]
I think I took this code from another package that did the same thing in order to make it work when there were a lot of ios widgets missing. I am thinking of removing this or at least offer a configuration option to still keep it for backward compatibility

**Comment by aqwert** [comment]
I have published v 0.31.0. Can you check if this resolves your issue.

**Comment by Valentin-Seehausen** [comment]
Guess this is the same issue as in #117 that resolves back to flutter/flutter#48438.

So this might also be closed by now?
