### ISSUE TITLE
On Ios when dark mode is enabled, text is shown dark, making text invisible

### ISSUE THREAD

**Issue by andreacimino** [aqwert/flutter_platform_widgets#117]
As in the title, here a attached the default app generated by flutter and modified in order to be used with the library that exhibits the problem. With the Standard Cupertino Scaffold/App, the problem is not shown.

[main.dart.zip](https://github.com/aqwert/flutter_platform_widgets/files/4028609/main.dart.zip)

**Comment by aqwert** [comment]
Looks like it is due to this https://github.com/aqwert/flutter_platform_widgets/issues/114. Working on fixing that

**Comment by aqwert** [comment]
I have published v 0.31.0. Can you check if this resolves your issue.

**Comment by andreacimino** [comment]
Yes, seems the issue, is fixed. Thank you very much.

**Comment by andreacimino** [comment]
Update: unfortunately the updated version does not work.
It work if i put the option:

/*          ios: (BuildContext context) {
                    return CupertinoAppData(
                        theme: CupertinoThemeData(brightness: Brightness.dark));
                  },  */
in the Platform app.

In case this is not set, the text still is shown dark.
In the day, obviously the text is visible, but in the night no.

**Comment by andreacimino** [comment]
Here seems to be the culprit:

print(DefaultTextStyle.of(context))
flutter: DefaultTextStyle(inherit: false, color: label(*color = Color(0xff000000)*, darkColor = Color(0xffffffff), resolved by: Builder), family: .SF Pro Text, size: 17.0, letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
null

The default text style selected is *color*, not darkColor. This is shown by the asterisks surrounding the print command.

**Comment by andreacimino** [comment]
By making some experiments, seems an upstream bug.  I will report progresses here.

**Comment by andreacimino** [comment]
Link to the issue:

https://github.com/flutter/flutter/issues/48438

**Comment by aqwert** [comment]
Thanks. I got the example showing Cupertino in dark mode when switching to it (for some reason I cannot get material to be dark which is strange as a project I have that uses platform widgets happily shows dark mode for material 🤷‍♂)

**Comment by aqwert** [comment]
FYI I have fixed the example.

Since this is a flutter reported issue can we close this issue as there is not much we can do about that here?

**Comment by Valentin-Seehausen** [comment]
#120 I guess both can be closed.
