### ISSUE TITLE
localization example code errors

### ISSUE THREAD

**Issue by fredgrott** [aqwert/flutter_platform_widgets#123]
Okay, got my listTile Listview on ios fixed I think once I have the localization errors solved..

on ios we have to use Cupertino localizations

error message is this

No MaterialLocalizations found. OverlayEntry widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.

which would be at the platform app stage of the example code in that

one would have to do for the CupertinoApp:

``CupertinoApp(
  localizationsDelegates: [
    DefaultMaterialLocalizations.delegate,
    DefaultCupertinoLocalizations.delegate,
    DefaultWidgetsLocalizations.delegate,
  ],
),

that should fix the error as far as the example code on ios

**Comment by fredgrott** [comment]
add the above lines in platformapp block in main.dart file in the example as it gets rid of localization error on ios so once thais done can close this isue

**Comment by fredgrott** [comment]
okay did the pr for it   so once that is merged we can close this issue

**Comment by aqwert** [comment]
PR Merged as it is part of the examples I won't ship a new version
