### ISSUE TITLE
2 errors left on code example version 0.32

### ISSUE THREAD

**Issue by fredgrott** [aqwert/flutter_platform_widgets#124]
Okay two errors left on android this time instead of ios. Ios problems of list tile solved with the add of container but one still has to add the 3 defautllocalization lines to platformapp block

Error One

PlatformTextField in main about line 299

error is dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
 tracking back to that line

Error Two

dark and light mode does not toggle as of yet like it should  no change in visuals when toggle is clicked

**Comment by fredgrott** [comment]
on the android dark-light error I have one more avenue to check, ie what shows up as far as system settings in the sysem settings drawer on android. will post back what I find

**Comment by aqwert** [comment]
I am starting to go through the properties of each widget. I do notice that the flutter team add or even change them so I need to make sure they are kept in sync

**Comment by aqwert** [comment]
I have updated the properties which hopefully fix the first issue you mentioned.

**Comment by aqwert** [comment]
see that the error you reported is a flutter issue. See here: https://github.com/flutter/flutter/issues/47343

**Comment by aqwert** [comment]
I have fixed the dark/light theme in the example.

**Comment by aqwert** [comment]
Can you confirm this is still an issue, otherwise I will close it.

**Comment by fredgrott** [comment]
cole it everything looks fine now as no errors, thanks
