### ISSUE TITLE
How to make an InkWell?

### ISSUE THREAD

**Issue by rocboronat** [aqwert/flutter_platform_widgets#147]
As the InkWell is something pure Material there's not a PlatformInkWell widget there.

What could be a good approach?

Thanks for this great project!

**Comment by rocboronat** [comment]
I went on with this approach:

```
Widget buildProfileItem(IconData icon, String text, Function onItemListener) {
  return PlatformWidget(
    android: (_) => InkWell(
      onTap: onItemListener,
      child: clickableRow(icon, text),
    ),
    ios: (_) => GestureDetector(
      onTap: onItemListener,
      child: clickableRow(icon, text),
    ),
  );
}
```

Is it a good approach? Maybe we could do a PlatformSomething that just has it?

Thanks again! 😄

**Comment by fredgrott** [comment]
you need to wrap it with Material widget

**Comment by rocboronat** [comment]
Oh, sorry! The issue is not that great. The idea was to create a PlatformInkwell also working on iOS. On Cupertino they don't have InkWells because it's Material, but it would be great that this library offered an PlatformInkWell that showed any kind of touch feedback on Cupertino while showing the ink effect on Material.

**Comment by aqwert** [comment]
From what I understand is that `GestureDetector` does not offer any visual feedback. Ideally this project works with widgets that exist on both Material and Cupertino packages. Otherwise it becomes a bit too opinionated and may work only for some people.

**Comment by rocboronat** [comment]
Oh, ok. Well, think about it. Maybe you (we if you want 😄 ) could create another category for those Widgets that are pure material in one side and _something opinionated_ in the other one.

**Comment by Valentin-Seehausen** [comment]
Hey, I also stumbled upon this issue. The Case is:

I want to have an onTap Event.
I want it to have an InkWell Effect on Android.
I don't want to have any visual effect on iOS.
I want to have one child Element and no code duplication further down the tree.

The opt-in approach of the PlatformButton could a great solution.

Proposal: 
```
PlatformGestureDetector(
  onTab: () {},
  androidInkWell: (_) => InkWellData(), // this will create an Inkwell on Android
  ios: (_) => GestureDetectorData(), // not sure if this is needed
  android: (_) => GestureDetectorData(), // not sure if this is needed
  child: Text('click me') // gets handed down to InkWell on Android and GestureDetector on iOS
)
```

I would love to contribute this, as this library is really useful and I am using it a lot. I actually think this makes Flutter even more multiplatform than Flutter itself and this library might be merged or be an example for further developments.

This is why I can see a big benefit in this kind of new category that takes into account the two different design approaches of the two platforms. If this is not accepted in this library, which would totally make sense, I would be willing to think together about finding an approach to the "two different design paradigma" problem with a new library.

**Comment by Valentin-Seehausen** [comment]
> Oh, sorry! The issue is not that great. The idea was to create a PlatformInkwell also working on iOS. On Cupertino they don't have InkWells because it's Material, but it would be great that this library offered an PlatformInkWell that showed any kind of touch feedback on Cupertino while showing the ink effect on Material.

And this is really working on iOS if you wrap the InkWell with a Material:

```
Material(
  child: InkWell(
    onTap: () {},
    child: Text('click me');
  )
);
```

But I guess you did know this already? I have this InkWell Effect on iOS, you can have it, I don't want it. :-P

**Comment by aqwert** [comment]
Since the Cupertino library does not have an equivalent to material `InkWell` I am unable to add a PlatformWidget for it. if there is (and I don't know about it) let me know so I can look at adding it
