### ISSUE TITLE
Settings Screen

### ISSUE THREAD

**Issue by MichaelPriebe** [aqwert/flutter_platform_widgets#149]
It would be super useful to be able to have a platform ware settings screen. https://pub.dev/packages/settings_ui does it very nicely, but has some unwanted features that do not work well with flutter_platform_widgets, for example the forced dark-mode awareness (I want to make a settings screen to add manual dark mode) and the inability to override the platform.

**Comment by aqwert** [comment]
Not sure about doing a whole settings page. Perhaps raise an issue there so it uses the `Theme.of(context).platform` rather than `Platform.isIOS` and `Platform.isAndroid` (https://github.com/yako-dev/flutter-settings-ui/blob/master/lib/src/settings_section.dart#L22) and to better support Dark mode

**Comment by Valentin-Seehausen** [comment]
Also consider using the systems dark mode, because this is how it is intended to be. And this might actually have consequences in the store approvals in the future (a *very very personal* assumption, not to take granted!)

**Comment by aqwert** [comment]
Closing as this project is not designed to build a page like this.
