### ISSUE TITLE
Solid background color for CupertinoNavigationBarData results in extra top padding

### ISSUE THREAD

**Issue by aaronfg** [aqwert/flutter_platform_widgets#15]
If you set the `backgroundColor` property on `CupertinoNavigationBarData` the body of the `PlatformScaffold` will too much top padding (perhaps doubling the safe area top?)

I made a test where you can swap between translucent (the default) and solid bg colors and see the bug.

Here's the code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_platform_widgets/flutter_platform_widgets.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Test(),
    );
  }
}

class Test extends StatefulWidget {

  Test({Key key}) :
        super(key: key);

  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {

  bool solidNav = false;

  @override
  Widget build(BuildContext context) {
    return PlatformScaffold(
      appBar: _buildAppBar(),
      body: _buildBody(),
    );
  }

  Widget _buildAppBar() {
    return PlatformAppBar(
      title: Text("test",
        style: Theme.of(context).textTheme.title.copyWith(
          color: solidNav ? Colors.white : Colors.black,
        ),
      ),
      ios: (BuildContext context) => _buildAppBariOS(),
    );
  }


  CupertinoNavigationBarData _buildAppBariOS() {
    return CupertinoNavigationBarData(
      backgroundColor: solidNav ? Colors.black : null,
    );
  }

  Widget _buildBody(){
    return SafeArea(
      child: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              child: Text("Solid navbar"),
              onPressed: (){
                setState(() {
                  solidNav = true;
                });
              },
            ),
            RaisedButton(
              child: Text("Translucent navbar"),
              onPressed: (){
                setState(() {
                  solidNav = false;
                });
              },
            ),
          ],
        ),
      ),
    );
  }
}
```

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.11.3, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.28.2)
[✓] Connected device (2 available)

• No issues found!

**Comment by aaronfg** [comment]
Any word on this?

**Comment by aqwert** [comment]
I have looked over this. the Flutter team have changed the way the CupertinoPageScaffold works. I need to spend a little more time on it than I though.

If you use the Cupertino widgets directly setting the header color does change the page layout a bit.

**Comment by aqwert** [comment]
I have published version 0.5.0 that should work in your case now

**Comment by aaronfg** [comment]
Seems it still has a problem if your scaffold body uses a safe area.  Less of a gap, but still a gap.

I'll make a new issue for this.

**Comment by aqwert** [comment]
I am thinking of raising a flutter issue as the padding is coming from flutter's Cupertino widget
