### ISSUE TITLE
Enable support for drawer in PlatformScaffold

### ISSUE THREAD

**Issue by msdate** [aqwert/flutter_platform_widgets#151]
Given that android enables use of drawers, drawers should be supported by PlatformScaffold.

ios does not recommend use of drawer, however we should still be able to optionally provide null to support Cupertino pattern 100%, or continue using drawers if the app requires it to do so. 

Currently, we are unable to use PlatformScaffold as it will not support the appDrawer tag.

**Comment by aqwert** [comment]
You can access the Drawer properties like so:

```
PlatformScaffold(
    android: (_) => MaterialScaffoldData(
        drawer: Drawer(...),
        endDrawer: Drawer(...),
    ),
);

**Comment by msdate** [comment]
Thanks.
