### ISSUE TITLE
PlatformButton MaterialRaisedButtonData no borderRadius

### ISSUE THREAD

**Issue by aelahmar** [aqwert/flutter_platform_widgets#153]
I can't set borderRadius for MaterialButtons ..

Thanks,

**Comment by aqwert** [comment]
I do not see any `borderRadius` property on the Material buttons within the flutter material package. Can you provide more information as to which flutter channel and version you are using.

**Comment by aelahmar** [comment]
`    Material materialButton = Material(
        elevation: 5.0,
        borderRadius: BorderRadius.circular(5.0),
        child: MaterialButton(
          padding: EdgeInsets.fromLTRB(20.0, 15.0, 20.0, 15.0),
          onPressed: onPressed,
          child: Text("Button"),
        ));`

**Comment by aqwert** [comment]
Could you please provide an example that uses this widgets from this project. I am not sure what you are trying to do.
