### ISSUE TITLE
Because union_flutter depends on flutter_platform_widgets

### ISSUE THREAD

**Issue by DavidMGT** [aqwert/flutter_platform_widgets#154]
Because union_flutter depends on flutter_platform_widgets >=0.30.0 which requires Flutter SDK version >=1.12.13+hotfix.2 <2.0.0, version solving failed.
how to fix this?who can help

**Comment by aqwert** [comment]
What is union_flutter> I am not familiar with that.

Perhaps have a look at this answer on stackoverflow: https://stackoverflow.com/questions/59548782/dart-packages-dependency-conflicts

**Comment by aqwert** [comment]
closing as this to do with another package
