### ISSUE TITLE
Class 'OrgList' has no instance method '[]'.

### ISSUE THREAD

**Issue by hihassam** [aqwert/flutter_platform_widgets#164]
here is class definition:

class OrgList {
  String display;
  String value;

  OrgList(this.display, this.value);
}

here is how I am populating one of its instance

   List<OrgList> menuItems = new List<OrgList>();
    for (int i = 0; i < orgItem.length; i++) {
      menuItems.add(OrgList(orgItem[i].id, orgItem[i].title));

    }

The list displays proper results but when i use the above list in DropDownFormField data source i get the above error "Class 'OrgList' has no instnace method []"

Container(
                      padding: EdgeInsets.all(16),
                      child: DropDownFormField(
                        titleText: 'Organizationattr',
                        hintText: 'Select Organization',
                        value: _myOrg,
                        onChanged: (value) {
                          setState(() {
                            _myOrg = value;
                          });
                          print(_myOrg);
                        },
                        onSaved: (value) {
                          _editedEvent = Event(
                              title: _editedEvent.title,
                              //   price: _editedEvent.price,
                              orgTitle: value,
                              orgId: value,
                              description: _editedEvent.description,
                              address: _editedEvent.address,
                              country: _editedEvent.country,
                              state: _editedEvent.state,
                              city: _editedEvent.city,
                              postalCode: _editedEvent.postalCode,
                              imageUrl: _editedEvent.imageUrl,
                              id: _editedEvent.id,
                              isFavorite: _editedEvent.isFavorite);
                        },
                        dataSource: menuItems
                                            ,
                        textField: 'display',
                        valueField: 'value',
                      ),
                    ),
       
here is the error details

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building DropDownFormField(dirty, dependencies: [_FormScope], state: FormFieldState<dynamic>#2ec3c):
Class 'OrgList' has no instance method '[]'.
Receiver: Instance of 'OrgList'
Tried calling: []("value")

here is what i have in pubspec

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.0.0
# intl: ^0.15.8
  intl: ^0.16.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  dropdown_formfield: ^0.1.2
  flutter_form_builder: ^3.8.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

**Comment by glofru** [comment]
Please format properly the code, or paste it into [pastebin.com](url)

**Comment by aqwert** [comment]
Closing as the code supplied (thou not formatted) does not include anything from this project. If you can provide a better example that does include `flutter_platform_widgets` and experiencing an issue then raise another issue
