### ISSUE TITLE
PlatformTabScaffold

### ISSUE THREAD

**Issue by alanmeier** [aqwert/flutter_platform_widgets#168]
Hi there,

This looks to be an issue with extra builds being done unnecessarily by the PlatformTabScaffold, currently testing on IOS. I have 5 tabs in my app and below is what happens as far as the number of page build requests for the bodyBuilder function. Surely the only requirement is to build the single screen that requires to be displayed when the index changes or is this a flutter issue or do I need to check what index is being passed and exclude any items that are not the current index ?

thanks
Alan

Restarted application in 1,584ms.
//Tab 0 Initial
flutter: tabbed_navigation init
flutter: TabItem.values index=0
flutter: TabItem.values index=0

// Tab 1 pressed
flutter: TabItem.values index=0
flutter: TabItem.values index=1

// Tab 2 pressed
flutter: TabItem.values index=0
flutter: TabItem.values index=1
flutter: TabItem.values index=2

// Tab 3 pressed
flutter: TabItem.values index=0
flutter: TabItem.values index=1
flutter: TabItem.values index=2
flutter: TabItem.values index=3

// Tab 4 pressed
flutter: TabItem.values index=0
flutter: TabItem.values index=1
flutter: TabItem.values index=2
flutter: TabItem.values index=3
flutter: TabItem.values index=4

Code for above
class TabbedPage extends StatefulWidget {
  @override
  TabbedPageState createState() {
    return new TabbedPageState();
  }
}

class TabbedPageState extends State<TabbedPage> {
  Globals globals;

  // This needs to be captured here in a stateful widget
  PlatformTabController tabController;

  @override
  void initState() {
    super.initState();

    // If you want further control of the tabs have one of these
    if (tabController == null) {
      tabController = PlatformTabController(
        initialIndex: 0,
      );
    }
  }

  Widget _selectPage(int index, bool isMaterial) {
    print('TabItem.values index=$index');

    // Save the preferences if we need to
    if (globals.preferences.needToSave) {
      final Database database = Provider.of<Database>(context, listen: false);
      database.savePreferences(globals.preferences);
    }

    TabItem tabItem = TabItem.values[index];
    switch (tabItem) {
      case TabItem.course:
        // Course
        return Center(child: null);
        break;
      case TabItem.meditation:
        // Meditations
        return Center(child: null);
        break;
      case TabItem.music:
        // Music
        return Center(child: null);
        break;
      case TabItem.sleep:
        // Sleep
        return Center(child: null);
        break;
      case TabItem.more:
        // Settings
        return SettingsPage(isMaterial);
        break;
      default:
        return null;
        break;
    }
  }

  BottomNavigationBarItem _navigationBarItemBuilder(TabItem tabItem) {
    final itemData = TabItemData.allTabs[tabItem];
    return BottomNavigationBarItem(
      title: Text(itemData.title),
      icon: PlatformWidget(
        ios: (_) => Icon(itemData.iosIcon),
        android: (_) => Icon(itemData.materialIcon),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    print('tabbed_navigation init');
    globals = Provider.of<Globals>(context, listen: false);
    if (!globals.initialised) {
      globals.initialise(context);
    }

    return PlatformTabScaffold(
      iosContentPadding: true,
      tabController: tabController,
      bodyBuilder: (context, index) => _selectPage(index, !globals.usingIOS),
      items: [
        _navigationBarItemBuilder(TabItem.course),
        _navigationBarItemBuilder(TabItem.meditation),
        _navigationBarItemBuilder(TabItem.music),
        _navigationBarItemBuilder(TabItem.sleep),
        _navigationBarItemBuilder(TabItem.more),
      ],
      ios: (_) => CupertinoTabScaffoldData(
        //   Having this property as false (default true) forces it not to use CupertinoTabView which will show
        //   the back button, but does required transitionBetweenRoutes set to false (see above)
        useCupertinoTabView: false,
      ),
    );
  }
}

**Comment by alanmeier** [comment]
Error on my part

**Comment by DFelten** [comment]
What was your solution? I have the same behavior.
