### ISSUE TITLE
How can i use Drawer inside PlatformScaffold?

### ISSUE THREAD

**Issue by kimbummen** [aqwert/flutter_platform_widgets#18]

**Comment by bottlenosecreative** [comment]
There doesn't appear to be a way to programatically open the drawer with this method? Can't access Scaffold.of(context).openDrawer(); 

Any thoughts?

**Comment by aqwert** [comment]
As long as the Widget is part of the BuildContext and you are on Android then you should be able to do it. You can use `Builder` which should give you access to the BuildContext with the scaffold on it

```
     body: Builder(
           builder: (BuildContext context) => ...
```

**Comment by aqwert** [comment]
OK, Been playing with it and with the example I have all you need to do is wrap a `Builder` instance around the button you want to open

This is on the trailingActions on the `PlatformAppBar`
```
trailingActions: <Widget>[
        Builder(
          builder: (BuildContext context) => PlatformIconButton(
                onPressed: () {
                  Scaffold.of(context).openDrawer();
                },
                iosIcon: Icon(
                  CupertinoIcons.share,
                  size: 28.0,
                ),
                androidIcon: Icon(
                     Icons.share,
                ),
              ),
        ),
```

**Comment by bottlenosecreative** [comment]
> OK, Been playing with it and with the example I have all you need to do is wrap a `Builder` instance around the button you want to open
> 
> This is on the trailingActions on the `PlatformAppBar`
> 
> ```
> trailingActions: <Widget>[
>         Builder(
>           builder: (BuildContext context) => PlatformIconButton(
>                 onPressed: () {
>                   Scaffold.of(context).openDrawer();
>                 },
>                 iosIcon: Icon(
>                   CupertinoIcons.share,
>                   size: 28.0,
>                 ),
>                 androidIcon: Icon(
>                      Icons.share,
>                 ),
>               ),
>         ),
> ```

I'll have a play with this tonight, I hadn't thought to use a builder inside the appBar

I'll let you know if it works in my situation

**Comment by aqwert** [comment]
I am closing this issue for now, unless you continue to have issues with this.
