### ISSUE TITLE
Web support Error: Type 'ActionFactory' not found.

### ISSUE THREAD

**Issue by AMarquitti** [aqwert/flutter_platform_widgets#184]
Hello, I know I´m running in beta channel in a web compiler, I submit this only in a constructive way, I removed the 'actions' and the web compiler successful. Thank you very much for your work.

Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-AR)
    • Flutter version 1.18.0-11.1.pre at /Users/alejandro.sosa/SDK/Flutter/flutter
    • Framework revision 2738a1148b (6 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

/flutter_platform_widgets-0.41.0/lib/src/platform_app.dart:95:21:
Error: Type 'ActionFactory' not found.
      Map<LocalKey, ActionFactory> actions,

**Comment by aqwert** [comment]
Master only supports the stable version of flutter which is currently 1.17.1.

I plan on creating a beta branch to sync up with the flutter beta channel but that might be a few days away

**Comment by aqwert** [comment]
I have created a beta branch that you can reference.
