### ISSUE TITLE
PlatformTabScaffold background colour

### ISSUE THREAD

**Issue by alanmeier** [aqwert/flutter_platform_widgets#187]
Can you tell me how I set the background colour of the PlatformTabScaffold on Android devices ?

I have tried all the available colours that can be passed to PlatformTabScaffold and all the ones in the Theme as well but am unable to change it. So this is likely a bug.

On IOS I can set the colour via the theme without any problems.

Thanks
Alan

**Comment by aqwert** [comment]
The tabs have a `tabsBackgroundColor` and the page content has `pageBackgroundColor`. If that does not work could you paste some code. Thanks

**Comment by alanmeier** [comment]
I see where my error is. I kept thinking that it would inherit from the original App theme I set but it is completely separate and does not. Most other widgets are using the theme which is why it is confusing ? Colour is the main thing I have found confusing in using the package, i.e. Knowing what is and is not inherited from the main theme.

Thanks
