### ISSUE TITLE
Issue with MaterialLocalization?

### ISSUE THREAD

**Issue by mlava** [aqwert/flutter_platform_widgets#188]
Hi again,
I am getting an error thrown when trying to view my application on iOS. It works fine on android.
The layout/structure is:

PlatformApp
PlatformScaffold
PlatformAppBar
PlatformNavBar

body: PlatformScaffold
Form
Padding
SingleChildScrollView
Column
Material
Padding
Row 
Expanded
DropdownButton<String>

The error is as below:

```
No MaterialLocalizations found.
The ancestors of this widget were: 
  : Row
    direction: horizontal
    mainAxisAlignment: start
    crossAxisAlignment: center
    dependencies: [Directionality]
    renderObject: RenderFlex#2426d relayoutBoundary=up17 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE OVERFLOWING
  : Padding
    padding: EdgeInsets(0.0, 0.0, 0.0, 20.0)
    dependencies: [Directionality]
    renderObject: RenderPadding#a59c2 relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  : Material
    type: canvas
    color: Color(0xfffafafa)
    dependencies: [_EffectiveTickerMode, _LocalizationsScope-[GlobalKey#f63ef], _InheritedTheme]
    state: _MaterialState#69aac
  : Column
    direction: vertical
    mainAxisAlignment: start
    crossAxisAlignment: center
    renderObject: RenderFlex#7d8e5 relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  : SingleChildScrollView
    dependencies: [PrimaryScrollController]
  : Padding
    padding: EdgeInsets.all(20.0)
    dependencies: [Directionality]
    renderObject: RenderPadding#8afcc relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  : Form-[LabeledGlobalKey<FormState>#dea36]
    state: FormState#34568
  : PlatformScaffold
    dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#f63ef], _InheritedTheme]
  : FleischnerForm
    dependencies: [_LocalizationsScope-[GlobalKey#f63ef], _InheritedTheme]
    state: FleischnerState#2604c
  : PlatformScaffold
    dependencies: [MediaQuery, _LocalizationsScope-[GlobalKey#f63ef], _InheritedTheme]
  : Fleischner
    dependencies: [_LocalizationsScope-[GlobalKey#f63ef], _InheritedTheme]
  : PlatformApp
    dependencies: [_LocalizationsScope-[GlobalKey#a0bfb], _InheritedTheme]
  : MyApp
  : MaterialApp
    state: _MaterialAppState#779b8
  ...
The relevant error-causing widget was: 
  DropdownButton<String> 
```

I have tried changing to simple Scaffold (not PlatformScaffold) and you can see that I've added a Material widget above DropdownButton but it still throws the error.

Is this a flutter issue or to do with the Platform widgets?

**Comment by aqwert** [comment]
Since you are using a `PlatformApp` any use of a Material widget becomes a bit harder when viewed in iOS. `PlatformApp` under to hood will use `CupertinoApp` so you will need to manually set the localizations yourself. 

Have a look at the example which resolves this:  https://github.com/aqwert/flutter_platform_widgets/blob/5f9f9b659fad7689c8ce8f200fa84de6689a7eb3/example/lib/main.dart#L80

Also there is an answer on Stackoverflow: https://stackoverflow.com/a/55919047/373706

**Comment by mlava** [comment]
@aqwert 

It's in the docs! I'm so sorry, I didn't mean to waste your time.
Thanks for pointing me to the answer, and sorry again! :-)
