### ISSUE TITLE
Anyway to hook up platform detection to Android Studio's "Toggle Platform Mode"

### ISSUE THREAD

**Issue by firsthour** [aqwert/flutter_platform_widgets#19]
Android Studio has a button in the Flutter Inspector to toggle the platform between Android and iOS in the same emulator. Just seems to trigger a page rebuild which changes the result of Theme.of(context).platform between TargetPlatform.android and TargetPlatform.iOS.

It seems like your platform.dart triggers off a lower level check against sky_engine/lib/io/platform.dart's Platform. Between isAndroid and isIOS.

I know you have nice methods changeToMaterialPlatform and changeToCupertinoPlatform, but is there any way to tie the auto detection into the Theme's platform so that when I toggled the platform in Android Studio it also toggled the widgets provided by this package?

Thanks.

**Comment by stefanrusek** [comment]
My PR #76 fixes this.

**Comment by aqwert** [comment]
The changes to PlatformProvider should allow for this now
