### ISSUE TITLE
PlatformDialogAction iOS text color

### ISSUE THREAD

**Issue by jaumard** [aqwert/flutter_platform_widgets#2]
In Android the color of the text is the same as the primary color, but on iOS it stay blue. For me make sens that it take also the primary color for the text as iOS offer natively the tintColor to change that text. Because in 99% we want to get rid of this blue text to put our own color

**Comment by aqwert** [comment]
I believe at this stage this cannot be changed since the code uses is just a wrapper over the Material and Cupertino widgets. By the looks changing the color of the button is not exposed by the widget

**Comment by jaumard** [comment]
Ho ok, strange that it's not automatic then ^^ thanks
