### ISSUE TITLE
PlatformListTile Suggestion

### ISSUE THREAD

**Issue by acahir** [aqwert/flutter_platform_widgets#20]
I'm just starting to play with Flutter, and was slightly disappointed in the non-native UI on iOS without duplicating the UI widgets by default, so thanks for the work on this package!

As mentioned in your Known Issues section, ListTile is one of the widgets that requires a Material widget somewhere in the hierarchy (who knows why ListTile is inside Material when ListView is not. Another issue is the Ink touch animation built into ListTile which is also not native to iOS. I had some ideas on possible solutions:

1. Create a CupertinoListTile inside flutter_platform_widgets (maybe flutter will include it in the future). This could be used from a PlatformListTile widget for iOS, which could also automatically wrap that tile in a Material widget. 

What I don't like about that is every tile will have an extra Material Widget. 

2. A second option which is similar would be to again have a CupertinoListTile widget as part of this package, but also include a PlatformListView. On iOS this could return a Material widget as a wrapper around the whole Listview on iOS, so only one extra widget is generated. 

Either of these would also allow the InkWell splash animation to be disabled via [this](https://github.com/flutter/flutter/pull/16336#issuecomment-380915096) method for iOS.

I'm too new to Dart/Flutter to suggest implementing myself, but would be happy to contribute in other ways (testing/documentation) if it would help.

**Comment by aqwert** [comment]
What might be better the simplest solution is to use the link (actually a sublink) you provided to disable just the splash but still use the ListTile from material. [GistLink](https://gist.github.com/HansMuller/721b827a6c0300e2d57e86a65f599377).

From what I know the pure Material and Cupertino libraries cannot be fully separated as yet, so you will still need to reference Material somewhere to get an iOS to render.

**Comment by aqwert** [comment]
Having thought about this it probably better to make an enhancement to the flutter.io repo around a more iOS Cupertino List item rather than a specific widget here
