### ISSUE TITLE
Manually select platform

### ISSUE THREAD

**Issue by Ali-Azmoud** [aqwert/flutter_platform_widgets#21]
Hi

Is there anyway to manually select the platform ? so that `PlatformScaffold` and other platform-related widgets display the correct widget

I don't have a mac laptop and want to debug my ios-style app on my android then compile it on a mac device

**Comment by aqwert** [comment]
Sure, If you are on the Android emulator you can call `changeToCupertinoPlatform()` right at the beginning of the app to render the Cupertino widgets. Or if you look at the example it is also done on a button press

**Comment by aqwert** [comment]
I am closing this issue for now, unless you continue to have an issue in this area
