### ISSUE TITLE
[Feature Request] Add PlatformTextField and PlatformSwitch

### ISSUE THREAD

**Issue by Sh1d0w** [aqwert/flutter_platform_widgets#23]
It will be very useful when building forms:

Material - https://docs.flutter.io/flutter/material/TextField-class.html
Cupertino - https://docs.flutter.io/flutter/cupertino/CupertinoTextField-class.html

Material - https://docs.flutter.io/flutter/material/Switch-class.html
Cupertino - https://docs.flutter.io/flutter/cupertino/CupertinoSwitch-class.html

**Comment by aqwert** [comment]
I certainly need to add these. Will be looking at it soon. Just needing to prioritise work

**Comment by aqwert** [comment]
Version 0.7.0 has been published which has the PlatformSwitch

**Comment by aqwert** [comment]
Version 0.8.0 has been published which has the PlatformTextField
