### ISSUE TITLE
Breaks with the release candidate of flutter

### ISSUE THREAD

**Issue by blueneogeo** [aqwert/flutter_platform_widgets#3]

**Comment by aqwert** [comment]
Currently I have developed against the Beta release branch as that is the latest "stable". I presume you are referring to the development branch. Since flutter as a whole is not at v1, it is likely there will be API changes that break implementation.  With the level of changes the dev branch undergoes on a daily basis, I would not be able to offer support for that at this point in time.

**Comment by blueneogeo** [comment]
Very understandable. I added the request because I am using your library as I think it is excellent, and as it is I keep getting warnings from flutter how outdated my flutter install is.

Dev seems much more stable than master though, and the flutter team recommends using it. Master is the one that is constantly updated and breaking.

The only problem when upgrading seems to be that there is a notch property that changed.

**Comment by aqwert** [comment]
I could look at a Dev branch that targets the Dev branch of flutter. Would be a bit more overhead but if it adds value to people I could do it. Would be more prone to breaking as flutters dev branch is in flux. Would you think it be worth it?

**Comment by aqwert** [comment]
Another option would be to Fork and make changes locally at your end. Then you can git reference the project in the pubspec. You could then PR back into my dev branch if others want it.

**Comment by blueneogeo** [comment]
Ok, let me check if I can fork and fix it on my end then.

**Comment by blueneogeo** [comment]
I'm having trouble uploading my fix branch for some reason... However the fix is very simple, a property has been removed:

in platform_nav_bar.dart:104, remove this line:

hasNotch: data?.hasNotch ?? true,

And all seems well. I think it is also save to remove from the master, since it seems the property is optional anyway.

**Comment by kidcosmic** [comment]
This error is happening on my end too, this is on the master branch of flutter. Note that now the beta channel of flutter is now 579 commits behind the master channel of flutter, so updating this seems necessary at this point.

**Comment by aqwert** [comment]
I have Published version 0.3.0 to remove the hasNotch property. Please check if this is a-ok

**Comment by blueneogeo** [comment]
@aqwert works well! Thank you.
