### ISSUE TITLE
Undefined class CupertinoThemeData 

### ISSUE THREAD

**Issue by medyas** [aqwert/flutter_platform_widgets#38]
I was trying to run the example app but got this error:
```
error: Undefined class 'CupertinoThemeData'. (undefined_class at [example] example.dart:30)

info: The library 'package:flutter/cupertino.dart' doesn't export a member with the shown name 'CupertinoThemeData'. (undefined_shown_name at [example] example.dart:1)
```

**Comment by aqwert** [comment]
You need to either upgrade flutter to the latest version or downgrade this package to 0.9.0

See change log: https://pub.dartlang.org/packages/flutter_platform_widgets#-changelog-tab-

**Comment by medyas** [comment]
changed to beta version and it's working.
