### ISSUE TITLE
PlatformAlertDialog on Android: No named parameter with the name 'contentTextStyle'.

### ISSUE THREAD

**Issue by HoverAlex** [aqwert/flutter_platform_widgets#40]
When using PlatformAlertDialog on Android the AlertDialog constructor throws errors because the Parameter "contentTextStyle" does not exist on the constructor.

```
showPlatformDialog(
          context: context,
          builder: (context) => PlatformAlertDialog(
                title: Text('The title'),
                content: Text('The content'),
                actions: <Widget>[
                  PlatformDialogAction(
                    onPressed: () => Navigator.of(context).pop(false),
                    child: Text('Abort'),
                  ),
                  PlatformDialogAction(
                    onPressed: () => Navigator.of(context).pop(true),
                    child: Text('OK'),
                  ),
                ],
              ),
        )
```

This error appears:
`I/flutter ( 7198): Another exception was thrown: 'package:flutter_platform_widgets/src/platform_alert_dialog.dart': error: line 104 pos 9: file:///E:/dev/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.9.5/lib/src/platform_alert_dialog.dart:104:9: Error: No named parameter with the name 'contentTextStyle'.`

This is because `contentTextStyle` (as well as `backgroundColor`, `elevation` and `shape` don't exist on the constructor.

**Comment by aqwert** [comment]
Can you please paste the version of flutter you have `flutter --version`

I suspect you need to upgrade to the latest beta which is version `1.1.8`. This library will endevour to stay up with that version of flutter. If you are on an older version of flutter and don't want to upgrade, please use version 0.9.0 as described in the changelog https://pub.dartlang.org/packages/flutter_platform_widgets#-changelog-tab-

**Comment by HoverAlex** [comment]
It seems to work with 0.9.0. Thanks :)
