### ISSUE TITLE
PlatformScaffold: tabs on top for Android?

### ISSUE THREAD

**Issue by kerberjg** [aqwert/flutter_platform_widgets#41]
Recently we've started working on a few apps in Flutter, using PlatformWidgets as the base for our UI;
however, when exploring the UX patterns for iOS and Android, we've realized that the PlatformScaffold does not really behave in a platform-aware way, as in:

> Different sections on Android are organized as tabs on top of the app. Sections are organized as tabs on the bottom of the app on iOS.

(source: https://medium.com/@vedantha/interaction-design-patterns-ios-vs-android-111055f8a9b7)

At this point, we're wondering whether `bottomNavBar` shouldn't actually be a `tabBar` that would be automatically placed on the top in Android and on the bottom in iOS?

We've already started working on an implementation of this for our app, I can submit a PR more than gladly.

**Comment by aqwert** [comment]
I am happy to accept PRs that improve the library. If it ends up being a breaking change it may be better to have a side by side version of it.

**Comment by shadabunique** [comment]
@kerberjg  Regarding nav bar position, if you observe the latest youtube app , it has the navbar at the bottom. This is as per material design where you want to put the frequently accessible options either on bottom nav bar or in the drawer. 
The top tab bar in android should not be confused with app's bottom nav bar (applicable for whole app flow).

**Comment by aqwert** [comment]
Regarding what this library is about is just a wrapper to the underlying Material and Cupertino widgets. Looking at the material Scaffold it has is a bottomNavigationBar property and this is exposed through the PlatformScaffold. 

The code of PlatformScaffold matches near 1:1 that of the material Scaffold.
