### ISSUE TITLE
Switch Platform Question

### ISSUE THREAD

**Issue by giannissc** [aqwert/flutter_platform_widgets#43]
This issue is slightly related with #21. I was recently working on a university project and decided to use platform_widgets for easier cross platform support. I decided to implement a separate settings screen and add a change platform button under dev settings. However upon implementing that every time platform was changed I was navigating back to the main screen. As I understand `changeToCupertinoPlatform()` should be used in the beginning of the app but is there a way to do that and have the changes propagate in the root widget once the back button in the settings screen is pressed rather than jumping directly back?

**Comment by aqwert** [comment]
Sorry for the delay...

I have been thinking of having a root widget that would rerender when the platform changed (in fact calling it via inherited widget instead) but I have not had the time to do it. Issue is that in order for the app to switch platforms, the build method needs to be called on every page. This does not naturally happen on parent pages. 
It could look something like: (just top of my head)
```
// app
void build(BuildContext context) {
    PlatformProvider(
      builder: (BuildContext context) =>  PlatformApp(...)
   )
}

//settings page
void onChangeToCupertinoPlatform(BuildContext context) {
    PlatformProvider.of(context).changeToCupertinoPlatform()
}
```
This may or may not work, will have to build it to see.

**Comment by aqwert** [comment]
I have built locally something that would help this issue. Stay tuned

**Comment by biklas7** [comment]
@aqwert any news on this? It will be awesome if we could change platforms like that :muscle:

**Comment by aqwert** [comment]
Have merged in the PlatformProvider. v0.11.5 has been published

**Comment by biklas7** [comment]
I was trying to give the PlatformProvider a try today and it seems that your package has some problems and that version is not live yet. Check [pub.dev analysis tab](https://pub.dev/packages/flutter_platform_widgets#-analysis-tab-). Thanks for the update btw 👍

**Comment by aqwert** [comment]
ok, I will have a look... might be a merge issue.

**Comment by aqwert** [comment]
Seems like the pub store is using version 1.5.4-hotfix.2 instead of what I built it against for 1.6.2. This was the release before this update. Will need to resolve that first before getting this out

**Comment by aqwert** [comment]
Published v0.12.0 which targets the correct flutter version and also has the PlatformProvider

**Comment by biklas7** [comment]
Tested v0.12.0 and it's working perfectly, thanks! Already found some issues in my Cupertino widgets thanks to this 😅 

Since this is now done, is there a way to call the changeTo* functions when the "Toggle Platform Mode" option on Android Studio or the "iOS" option on Dart Dev Tools are clicked? Related to https://github.com/aqwert/flutter_platform_widgets/issues/19

**Comment by aqwert** [comment]
Closing as it addresses the original issue. Issue 19 is still open to address your additional comment
