### ISSUE TITLE
appbar trailing widget off center

### ISSUE THREAD

**Issue by Deftness** [aqwert/flutter_platform_widgets#44]
I can't believe I didn't think about googling for a package like this already existing.

Anyways, I am trying to implement a `PlatformAppBar` which has just a title and on the right it just has the word "Done" which is a PlatformButton. 

```
PlatformAppBar(
                                          title:
                                              PlatformText("Picture"),
                                          leading: Container(),
                                          trailingActions: <Widget>[
                                            PlatformButton(
                                                onPressed: () {
                                                  Navigator.pop(context);
                                                },
                                                child: PlatformText('Done'))
                                          ])
```

![image](https://user-images.githubusercontent.com/45775243/55686663-e6aedd80-5931-11e9-9481-3440932da540.png)

I think the `PlatformText` is off center vertically **(in relation to the title)** because typically it would be expecting I believe an Icon of roughly a fixed size? Anyways, I tried adding a Container with padding to offset it from the bottom, but was unable to do that.

My apologies if I missed some other flag I was supposed to set.

**Comment by aqwert** [comment]
I am unable to reproduce what you have but I have seen this in older versions of flutter. What version are you targeting?

With the latest flutter (Beta channel) I do get an issue with it pushing down too much but setting the padding to 0 works,

If not, then there might be something else causing it

```
appBar: PlatformAppBar(
        title: PlatformText('Picture'),
        trailingActions: <Widget>[
          PlatformButton(
              padding: const EdgeInsets.all(0),
              onPressed: () {
                Navigator.pop(context);
              },
              child: PlatformText('Done'))
        ],
      ),
```

**Comment by tmaihoff** [comment]
This issue is quite old but I also have this problem with flutter 3.3.6 and `flutter_platform_widgets: ^2.0.0`
```dart
    return PlatformIconButton(
      icon: const Icon(Icons.settings_outlined),
      // padding: EdgeInsets.zero,
```
<img width="427" alt="image" src="https://user-images.githubusercontent.com/44509310/199929606-80c08920-3e75-4cf6-b702-1a9bcbc24e86.png">

Setting the padding to zero works, but I feel like this should be centered out of the box.

**Comment by martin-braun** [comment]
Yes `padding: EdgeInsets.zero` solves it. 5 years, nobody ever bothered fixing the defaults of `PlatformIconButton` and whatnot in the `trailingActions` container, because it's such an easy fix with `padding: EdgeInsets.zero`. 

I'm guilty, too.

**Comment by martin-braun** [comment]
I built a widget to streamline the position of icon / text buttons in the app bar for both platforms:

```dart
class PlatformAppBarButton extends StatelessWidget {
  const PlatformAppBarButton({
    super.key,
    this.icon,
    this.text,
    this.color,
    this.onPressed,
  }) : assert((icon != null) != (text != null),
            'Either icon or text must be provided, but not both');

  final IconData? icon;
  final String? text;
  final Color? color;
  final VoidCallback? onPressed;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final bool onMaterial = isMaterial(context);
    if (this.icon != null) {
      // TODO(martin-braun): Use PlatformIconButton instead, wait for https://github.com/stryder-dev/flutter_platform_widgets/issues/458
      return IconButton(
          padding: EdgeInsets.zero,
          icon: Icon(
            this.icon,
            color: this.color ??
                (!onMaterial
                    ? theme.cupertinoOverrideTheme?.textTheme
                        ?.navActionTextStyle.color
                    : theme.appBarTheme.iconTheme?.color),
            size: onMaterial
                ? theme.appBarTheme.iconTheme?.size
                : () {
                    double? x = theme.cupertinoOverrideTheme?.textTheme
                        ?.navActionTextStyle.fontSize;
                    x = x != null ? x * 2 : null;
                    return x;
                  }(),
          ),
          onPressed: this.onPressed);
    }
    final TextStyle style = ((!onMaterial
            ? theme.cupertinoOverrideTheme?.textTheme?.navActionTextStyle
            : theme.appBarTheme.toolbarTextStyle) ??
        theme.textTheme.bodyLarge ??
        const TextStyle());
    return PlatformTextButton(
        padding: EdgeInsets.zero,
        onPressed: this.onPressed,
        child: Text(
          this.text!,
          style: this.icon != null
              ? style.copyWith(
                  color: this.color ?? theme.appBarTheme.iconTheme?.color)
              : style,
        ));
  }
}
```

Respects your material and cupertino theme and embeds the fix mentioned here:

<img width="157" alt="image" src="https://github.com/stryder-dev/flutter_platform_widgets/assets/24259245/40fc2040-eb12-4e2a-9249-4c5b84426d24">

```dart
        trailingActions: [
          PlatformAppBarButton(
            onPressed: () {
              Navigator.of(context).pop();
            },
            text: "pl10n(context, l10n, PlatformI10nKey.save)",
          ),
        ],
```

<img width="143" alt="image" src="https://github.com/stryder-dev/flutter_platform_widgets/assets/24259245/97cd9b95-da10-49d8-9311-ec876c6096e9">

```dart
        trailingActions: [
          Observer(
              builder: (context) => PlatformAppBarButton(
                  icon: Icons.signal_cellular_alt,
                  color: stateAppStatusStore.isOffline
                      ? theme.primaryColorLight
                      : null)),
        ],
```

Obviously you need a proper `ThemeData` initialization to make it work.
