### ISSUE TITLE
CupertinoTabScaffold multiple pages

### ISSUE THREAD

**Issue by benoitjadinon** [aqwert/flutter_platform_widgets#45]
Whenever you set a `bottomNavBar` on ios, the `CupertinoPageScaffold` creates a `CupertinoTabScaffold`, but its tabBuilder recreates a new `CupertinoPageScaffold` on each tab click without using the `index` argument, so it just basically duplicates the `body`, making the nav bar useless. 
Any idea on how to handle ios navigation ? a callback inside `CupertinoPageScaffoldData` ?
thanks

**Comment by aqwert** [comment]
I will need to look into this a little more. Hopefully in the next few days.

in the meantime could you provide sample code of how you are using it?

**Comment by aqwert** [comment]
I found the issue you are experiencing. Will be getting a fix out soon

**Comment by benoitjadinon** [comment]
sure, I see it works within a sample project, it must be a special case from my project, I'm investigating, thx

**Comment by benoitjadinon** [comment]
ok it's when using a body with a GlobalKey, I get a `"Multiple widgets used with the same GlobalKey"` error, the current body of the `platformscaffold` is also used as a `CupertinoPageScaffold` child (`Widget child = body ?? data?.body;`) for the newly created CupertinoPageScaffold after a click on a tab, so they maybe both exist at the same time (even for a millisecond before the new body is recalculated), creating this error, that's why the second page also showed the body of the first tab (default body)

I probably shouldn't have used a GlobalKey there (because I had a scaffold as the body of an other one, to get an inside drawer),
about having the scaffold body as base for the other tab pages, at first I thought it was weird, but thinking of it, it's pretty clever ;-)
there may be no way simpler way to deal with it, because of the need for `CupertinoPageScaffold`

thanks

**Comment by benoitjadinon** [comment]
have you experienced the same issue ? what would the fix be ?

**Comment by nuzelac** [comment]
I think I am experiencing the same issue:

<img width="431" alt="iPhone 11 Pro Max — 13 0 2019-09-25 19-38-00" src="https://user-images.githubusercontent.com/195299/65625406-1333e000-dfcc-11e9-83b9-01cb32206a16.png">

**Comment by youannis-aziz** [comment]
Anybody found a solution for this issue?

**Comment by aqwert** [comment]
Can you post sample code that displays this issue

**Comment by youannis-aziz** [comment]
Just used PlatformTabScaffold with PlatformTabController as in the example: 
[example/lib/tabbed/basicTabbedPage.dart](https://github.com/stryder-dev/flutter_platform_widgets/blob/4a19971aa888cf4ca07dc767f0c9521e69451023/example/lib/tabbed/basicTabbedPage.dar)

It works fine on Android but on iOS other tabs also showed the body of the first tab and I got the below exception:

> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.
The key [LabeledGlobalKey<NavigatorState>#d20c9] was used by multiple widgets. The parents of those
widgets were:
- ModularProvider(state: _ModularProviderState#425b4)
- ModularProvider(state: _ModularProviderState#e8bfb)
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
#0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:249:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:196:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:192:26)
#5      GlobalKey._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:257:6)
#6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2758:21)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2839:8)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:18)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
#16     _invoke (dart:ui/hooks.dart:253:10)
#17     _drawFrame (dart:ui/hooks.dart:211:3)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<NavigatorState>#d20c9] was used by multiple widgets. The parents of those widgets were:
- ModularProvider(state: _ModularProviderState#425b4)
- ModularProvider(state: _ModularProviderState#e8bfb)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:249:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:196:20)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:192:26)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Multiple widgets used the same GlobalKey.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by youannis-aziz** [comment]
Just used PlatformTabScaffold with PlatformTabController as in the example:
example/lib/tabbed/basicTabbedPage.dart

It works fine on Android but on iOS other tabs also showed the body of the first tab and I got the below exception:

> 
> ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
> The following assertion was thrown while finalizing the widget tree:
> Multiple widgets used the same GlobalKey.
> The key [LabeledGlobalKey<NavigatorState>#d20c9] was used by multiple widgets. The parents of those
> widgets were:
> A GlobalKey can only be specified on one widget at a time in the widget tree.
> 
> When the exception was thrown, this was the stack:
> #0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:249:13)
> #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:196:20)
> #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:192:26)
> #5      GlobalKey._debugVerifyGlobalKeyReservation (package:flutter/src/widgets/framework.dart:257:6)
> #6      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2758:21)
> #7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2839:8)
> #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:868:18)
> #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
> #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
> #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
> #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
> #16     _invoke (dart:ui/hooks.dart:253:10)
> #17     _drawFrame (dart:ui/hooks.dart:211:3)
> (elided 3 frames from dart:async)
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> The following assertion was thrown while finalizing the widget tree:
> Multiple widgets used the same GlobalKey.
> 
> The key [LabeledGlobalKey<NavigatorState>#d20c9] was used by multiple widgets. The parents of those widgets were:
> A GlobalKey can only be specified on one widget at a time in the widget tree.
> When the exception was thrown, this was the stack: 
> #0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:249:13)
> #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:196:20)
> #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
> #4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:192:26)
> ...
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> 
> Another exception was thrown: Multiple widgets used the same GlobalKey.
> 
> ════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
> Multiple widgets used the same GlobalKey.
> ════════════════════════════════════════════════════════════════════════════════════════════════════
>

**Comment by youannis-aziz** [comment]
Sorry it was a conflict with other package [flutter_modular](https://pub.dev/packages/flutter_modular) on iOS only

**Comment by deakjahn** [comment]
It's basically completely wrong, yes. One workaround could be to make sure you pass a `PageView` in this case as the body of your scaffold and modify the code to extract the page in question (in `createIosWidget()`):

    child: iosContentPad(context, (body as PageView).childrenDelegate.build(context, index), navigationBar, tabBar),
