### ISSUE TITLE
Support for Desktop

### ISSUE THREAD

**Issue by AppleEducate** [aqwert/flutter_platform_widgets#46]
Flutter is now officially supporting desktop app. You can currently run `flutter run -d macos` on the master branch of flutter.

Windows and Linux Platform should display Android/Material.

Mac Target Should display Cupertino.

Here is how we set it in the main.dart of the example or app we are running.

``` dart
void main() {
  // Desktop platforms aren't a valid platform.
  _setTargetPlatformForDesktop();

  return runApp(MyApp());
}

/// If the current platform is desktop, override the default platform to
/// a supported platform (iOS for macOS, Android for Linux and Windows).
/// Otherwise, do nothing.
void _setTargetPlatformForDesktop() {
  TargetPlatform targetPlatform;
  if (Platform.isMacOS) {
    targetPlatform = TargetPlatform.iOS;
  } else if (Platform.isLinux || Platform.isWindows) {
    targetPlatform = TargetPlatform.android;
  }
  if (targetPlatform != null) {
    debugDefaultTargetPlatformOverride = targetPlatform;
  }
}
```

**Comment by AppleEducate** [comment]
This issue is currently If you run flutter on the desktop on any platform other than android and ios the platform widget throws and error saying it is not supported.

**Comment by aqwert** [comment]
I can look at adding this in the next few days. Officially this package supports only the Beta channel, so anything on master I would not ordinarily provide a fix for. This however seems like a low risk change, but if there are any widget based issues that arise from code on master I would be hesitant to provide a fix for.

**Comment by AppleEducate** [comment]
Well all I need is that change. My package native_widgets depends on this one and that is where I will support all the changes. I just don’t need it throwing an error for the platform.

**Comment by aqwert** [comment]
I have just published v0.9.6 with those platforms. Could you verify.

**Comment by AppleEducate** [comment]
Will do, I'll report back soon

**Comment by AppleEducate** [comment]
Worked perfect! Thank you!
