### ISSUE TITLE
Cupertino "edge swipe" bug

### ISSUE THREAD

**Issue by Z6P0** [aqwert/flutter_platform_widgets#54]
Here is how to reproduce:
- Run the example code
- Switch platform to Cupertino
- Open tabbed page
- Select the Book tab
- Swipe from the left edge (back gesture)

Here is the error log:
I/flutter (23115): The following assertion was thrown while handling a gesture:
I/flutter (23115): There are multiple heroes that share the same tag within a subtree.
I/flutter (23115): Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must
I/flutter (23115): have a unique non-null tag.
I/flutter (23115): In this case, multiple heroes had the following tag: Default Hero tag for Cupertino navigation bars
I/flutter (23115): with navigator NavigatorState#174ca(tickers: tracking 2 tickers)
...

**Comment by aqwert** [comment]
I have corrected this in the package update v0.11.0
