### ISSUE TITLE
Can't copy into focussed PlatformTextField

### ISSUE THREAD

**Issue by nvbln** [aqwert/flutter_platform_widgets#56]
At least on the Android version of `PlatformTextField` it is not possible to copy text into the text field if the text field is already in focus (which also means that if `autofocus: true` is set it is never possible to copy text into the field). This is best reproducible by either typing something in, removing it, and then trying to copy in text or by simply using the `autofocus: true` property.

**Comment by aqwert** [comment]
There is nothing special happening with `PlatformTextField` it simply uses the material `TextField` directly. Could you see if the issue occurs on the material `TextField` itself without using this package?

Also what version of Flutter are you on?

**Comment by nvbln** [comment]
I can indeed reproduce this issue on the normal `TextField`. I'll open an issue upstream in that case. 
Also, I don't think it's very relevant anymore, but I am using version 1.6.7.
