### ISSUE TITLE
Remove forced text transformation

### ISSUE THREAD

**Issue by ioxua-os** [aqwert/flutter_platform_widgets#62]
So for some reason, PlatformText forcefully 'uppercases' any string inputted when used on Material mode.

I fixed this for my use case and I can submit a pull request if needed, but I would like to understand the rationale behind that decision.

**Comment by aqwert** [comment]
That is exactly what `PlatformText` is meant to do. In some cases you would want to render all uppercase for Android and not for iOS, particularly around buttons. So this widget just makes that easy to achieve without conditionals

If you don't want to uppercase for android then just use the standard `Text` widget,

**Comment by ioxua-os** [comment]
Oh, I see. Makes sense, thank you ^^

**Comment by WieFel** [comment]
Would there be a possibility to add a flag `useUppercase` to `PlatformText`?

In my use case I need to use `PlatformText` in order for the PlatformApp's theme to apply, but I still want the text to be the original string and not all uppercase.

**Comment by aqwert** [comment]
> Would there be a possibility to add a flag `useUppercase` to `PlatformText`?
> 
> In my use case I need to use `PlatformText` in order for the PlatformApp's theme to apply, but I still want the text to be the original string and not all uppercase.

I am not sure why you can't just use `Text`. There is nothing special about `PlatformText` other than make the string uppercase for android. Theming should work either way

**Comment by WieFel** [comment]
I don't know either, but on iOS `Text` is not applying the font family that I set in `CupertinoThemeData`. `PlatformText` **does** apply the text theme.
