### ISSUE TITLE
problem to apply theme in PlatformApp

### ISSUE THREAD

**Issue by liodali** [aqwert/flutter_platform_widgets#63]
how to make theme with platformwidget or PlatformApp ?

**Comment by uuttff8** [comment]
to implement, this should be used: https://api.flutter.dev/flutter/material/ThemeData/cupertinoOverrideTheme.html

**Comment by aqwert** [comment]
As @uuttff8 suggests you can use `cupertinoOverrideTheme`. If you need to style ios whilt using `MaterialApp`. According to the docs:

```
/// To override individual parts of the Material-derived Cupertino styling,
/// `cupertinoOverrideTheme`'s construction parameters can be used.
///
/// To completely decouple the Cupertino styling from Material theme derivation,
/// another [CupertinoTheme] widget can be inserted as a descendant of the
/// Material [Theme]. On a [MaterialApp], this can be done using the `builder`
/// parameter on the constructor.
```

If you are using `PlatformApp` you can see as part of the example that the `CupertinoApp.theme` needs a `CupertinoThemeData` which can be created specifically for itself.

I m not 100% on the ins and outs of it but the flutter docs are a good place to start
