### ISSUE TITLE
PlatformNavBar unaable to add 5 bottomNavButtons

### ISSUE THREAD

**Issue by shock-wave007** [aqwert/flutter_platform_widgets#68]
![Screenshot (13)_LI](https://user-images.githubusercontent.com/29371789/62454189-815ce300-b791-11e9-9349-3bd656fe8063.jpg)
![Screenshot (14)_LI](https://user-images.githubusercontent.com/29371789/62454190-815ce300-b791-11e9-81fd-a986163c7cfd.jpg)

when i try to add more than 3 bottomNavButtons in PlatformNavBar , navBar disappears. any suggestions or if iam doing something wrong.and there is no error

**Comment by aqwert** [comment]
That is apparently how it works. See this comment about the issue: https://github.com/flutter/flutter/issues/13642#issuecomment-371875044
