### ISSUE TITLE
Bug: Wrong Padding in PlatformScaffold

### ISSUE THREAD

**Issue by Hawlitschek** [aqwert/flutter_platform_widgets#7]
In order to decided whether padding is necessary or not, the **fullObstruction** is used.
It is defined the following (Cupertino):

`bool get fullObstruction => backgroundColor.alpha == 0xFF;`

When looking inside the PlatformScaffold there is the following code:

`if (!navigationBar.fullObstruction) {
        var pad = Padding(
          padding: EdgeInsets.only(top: topPadding),
          child: child,
        );
        child = pad;
      }`

Padding is added, if the bar is **is not** fullObstruction => When alpha != 0xFF.
This means padding is added when we want a nav bar where the user could look through.
Removing the **!** fixes the issue.

**Comment by aqwert** [comment]
Published fix v0.3.2
