### ISSUE TITLE
BottomNavBar for only iOS is impossible

### ISSUE THREAD

**Issue by calderwoodra** [aqwert/flutter_platform_widgets#72]
Currently it's not possible to generate an iOS app with a bottom nav bar and and Android app without one.

This was the code I tested:
```
PlatformScaffold(
  appBar: PlatformAppBar(title: PlatformText('TEST', ),),
  ios: (context) => CupertinoPageScaffoldData(
      bottomTabBar: CupertinoTabBar(
      items: <BottomNavigationBarItem>[
          BottomNavigationBarItem(
              title: PlatformText("Feed"),
              icon: Icon(Icons.subject),
           ),
          BottomNavigationBarItem(
              title: PlatformText("Settings"),
              icon: Icon(Icons.settings),
          ),
       ],
  )),
  body: Container(),
);
```

**Comment by aqwert** [comment]
In this case using PlatformScaffold may not be what you need. It maybe better to use PlatformWidget and use Material and Cupertino widgets directly. This library aims to provide a similar interface between ios and android. Having said that, I notice that perhaps it would be better to separate the PlatformScaffold into a Tabbed and NonTabbed version which I may put up at some stage.

**Comment by fredgrott** [comment]
@aqwert that was my next question  of how to do tabbed and you gave me a solution already great!
