### ISSUE TITLE
The following NoSuchMethodError was thrown building PlatformScaffold(dirty):

### ISSUE THREAD

**Issue by miroda** [aqwert/flutter_platform_widgets#74]
I/flutter (13031): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13031): The following NoSuchMethodError was thrown building PlatformScaffold(dirty):
I/flutter (13031): The method '>' was called on null.
I/flutter (13031): Receiver: null
I/flutter (13031): Tried calling: >(0)
I/flutter (13031): 
I/flutter (13031): When the exception was thrown, this was the stack:
I/flutter (13031): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (13031): #1      int.< (dart:core-patch/integers.dart:84:18)
I/flutter (13031): #2      int.<= (dart:core-patch/integers.dart:99:37)
I/flutter (13031): #3      new BottomNavigationBar (package:flutter/src/material/bottom_navigation_bar.dart:196:17)
I/flutter (13031): #4      PlatformNavBar.createAndroidWidget (package:flutter_platform_widgets/src/platform_nav_bar.dart:148:15)
I/flutter (13031): #5      PlatformScaffold.createAndroidWidget (package:flutter_platform_widgets/src/platform_scaffold.dart:136:47)
I/flutter (13031): #6      PlatformWidgetBase.build (package:flutter_platform_widgets/src/widget_base.dart:21:14)
I/flutter (13031): #7      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
I/flutter (13031): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (13031): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13031): #10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13031): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13031): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13031): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13031): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13031): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13031): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13031): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13031): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13031): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13031): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13031): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13031): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13031): #23     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (13031): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (13031): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (13031): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (13031): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (13031): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (13031): #32     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (13031): #33     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (13031): (elided 3 frames from package dart:async)

**Comment by miroda** [comment]
bottomNavBar: PlatformNavBar(
        currentIndex: _selectedTabIndex,
        itemChanged: (index) => setState(
          () {
            _selectedTabIndex = index;
          },
        ),
        items: [
          BottomNavigationBarItem(
              icon: Image.asset('images/icon_nav_bidprice_normal.png'),
              activeIcon: Image.asset('images/icon_nav_bidprice_selected.png'),
              title: Text('任务')),
          BottomNavigationBarItem(
              icon: Image.asset('images/icon_nav_transport_normal.png'),
              activeIcon: Image.asset('images/icon_nav_transport_selected.png'),
              title: Text('运力')),
          BottomNavigationBarItem(
              icon: Image.asset('images/icon_nav_welfare_normal.png'),
              activeIcon: Image.asset('images/icon_nav_welfare_selected.png'),
              title: _selectedTabIndex == 2 ? null : Text('福利')),
          BottomNavigationBarItem(
              icon: Image.asset('images/tab_income_normal.png'),
              activeIcon: Image.asset('images/tab_income_highlight.png'),
              title: Text('收入')),
          BottomNavigationBarItem(
              icon: Image.asset('images/icon_nav_my_normal.png'),
              activeIcon: Image.asset('images/icon_nav_my_selected.png'),
              title: Text('我的')),
        ],
      ),

**Comment by miroda** [comment]
![image](https://user-images.githubusercontent.com/2841126/63907373-be915980-ca4d-11e9-87e1-5b19c6504f9e.png)
This is my code ,I put BottomNavigationBarItem in PlatformNavBar,then when I run this on android,the bug came out.Does anyone has any idea?

**Comment by aqwert** [comment]
Does `_selectedTabIndex` have a value when the page loads. Could it be null?

Otherwise could you give a better example with code rather than a screenshot.

**Comment by aqwert** [comment]
If this is still an issue please update with a more complete example. If not I will be closing this issue.

**Comment by aqwert** [comment]
Without more information I am closing this issue. Feel free to reopen with a more complete example
