### ISSUE TITLE
[Question] Multiple heroes share the same tag within a subtree

### ISSUE THREAD

**Issue by VictorUvarov** [aqwert/flutter_platform_widgets#84]
Hello,
I was trying to implement your package into my little architecture app. [App](https://github.com/VictorUvarov/provider_architecture)

I get this error on iOS:
```
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.
```

I assume there is some Platform Widget that is complaining about keys. Not really sure where to start looking. Do you have any advice?

**Comment by VictorUvarov** [comment]
Turns out I was using an indexed stack for my PlatformNavBar items. Which contained multiple widgets.

**Comment by liepaja** [comment]
@VictorUvarov  can you please explain what issue you had? I experience same issue

**Comment by VictorUvarov** [comment]
I actually just disabled animation transitions for iOS data on platform app bars. Something with the animation breaks.

**Comment by Guillaume351** [comment]
I am having the same issue.
How to disable those animations ? Shouldn't this be an open issue instead of closed ?
Thanks

**Comment by aqwert** [comment]
Could you provide a sample code that causes this. Also if you use the underlying Material or Cupertino widgets do you still see the issue?

**Comment by VictorUvarov** [comment]
It was just a problem with my navigation service. I was using a global key of type GlobalKey<NavigatorState> to handle my navigation. The problem does not occur if you just using something like Navigator.of(context).push(....).
