### ISSUE TITLE
Bug with PlatformAlertDialog

### ISSUE THREAD

**Issue by KyllianDM** [aqwert/flutter_platform_widgets#85]
Hello,
There is a problem with the PlatformAlertDialog, just see the picture.
![Screenshot_20190924_223949](https://user-images.githubusercontent.com/9364594/65548857-9dbd0680-df1c-11e9-9570-389c82cd2fd2.jpg)

**Comment by aqwert** [comment]
Can you provide an example code

**Comment by KyllianDM** [comment]
`showPlatformDialog(
              context: context,
              builder: (_) => PlatformAlertDialog(
                      title: Text('Terminé'),
                      content: Text(
                          'Votre mot de passe a bien été modifié, vous pouvez l\'utiliser dès maintenant.'),
                      actions: [
                        PlatformDialogAction(
                            child: Text('Fermer'),
                            onPressed: () {
                              Navigator.pop(context);
                              Navigator.pop(context);
                            })
                      ]));`

**Comment by KyllianDM** [comment]
Hello,
Did you see my answer ?

**Comment by aqwert** [comment]
Sorry. been very busy. I won't get to this for a few days. I would be surprised that this is in this package as it is just a wrapper to the underlying material and cupertino equivalent. Could you build a Material dialog and see what that looks like

**Comment by feudadrien** [comment]
Why do you have two Navigator pops?
