### ISSUE TITLE
ObstructingPreferredSizeWidget Breakage

### ISSUE THREAD

**Issue by davidlantrip** [aqwert/flutter_platform_widgets#87]
I'm seeing some errors when building with the `master` channel. Looks like they renamed a property on `ObstructingPreferredSizeWidget` that causes a build error in `platform_scaffold.dart`.

```
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
      final obstruct = navigationBar.fullObstruction == null ||
                                     ^^^^^^^^^^^^^^^
```

https://github.com/flutter/flutter/commit/d8ca42e21165acc64c7b83af835982e91d79c6c5#diff-0cf6ecf096263d1f196f0b3a0c3063ce

**Comment by aqwert** [comment]
Master is not supported. There are too many changes to be able to support channels other than stable.

Best thing for you would be to folk the repo and get it to work against master
