### ISSUE TITLE
Same page transitions as MaterialPageRoute on IOS

### ISSUE THREAD

**Issue by liepaja** [aqwert/flutter_platform_widgets#94]
is there a way to navigate pageroute just like MaterialPageRoute is being navigated on IOS (parallax left to right )?

**Comment by VictorUvarov** [comment]
Yes, you can just always use CupertinoPageRoute for every route you have. Example of generating routes with CupertinoPageRoute:
### Main.dart
```dart
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
            title: 'App',
            onGenerateRoute: Router.generateRoute,
            home: HomeView(),
    );
  }
}
```

### Router
```dart
class Router {
  static Route<dynamic> generateRoute(RouteSettings settings ) {
    return CupertinoPageRoute(
      settings: RouteSettings(name: settings.name),
      builder: (context) => _generateView(settings),
    );
  }

  static Widget _generateView(RouteSettings settings) {
    switch (settings.name) {
      case 'home':
        return HomeView();
      default:
        return Scaffold(
          body: Center(
            child: Text('No route defined for ${settings.name}'),
          ),
        );
    }
  }
}
```

**Comment by liepaja** [comment]
The thing is that CupertinoPageRoute doesn't have the parallax effext as material route on ios.

**Comment by japborst** [comment]
Just use MaterialPageRoute then :)

**Comment by VictorUvarov** [comment]
Oh then maybe consider using a package for fancy navigation transitions. https://pub.dev/packages/page_transition

**Comment by liepaja** [comment]
@japborst If you read it carefully i mentioned that it only works for ios. 
@VictorUvarov thanks for follow up , did try , ExitEnter package, yet its implemented way differently, no parallax and the way navigation works just break bloc pattern

**Comment by japborst** [comment]
@liepaja if you want the iOS animation also to work for Android, you can override the platform in your theme so everything is iOS style. Otherwise you can also create a custom widget to override the theme for just the MaterialPageRoute.

**Comment by liepaja** [comment]
@japborst the first option is not sustainable, the second one would work, yet i can't find the code of that transition anywhere.

**Comment by liepaja** [comment]
The solution is to use CupertinoApp if somebody is wondering.
