### ISSUE TITLE
[Question] ThemeData/CupertinoThemeData

### ISSUE THREAD

**Issue by VictorUvarov** [aqwert/flutter_platform_widgets#95]
Is there support or plans to wrap both `ThemeData` and `CupertinoThemeData`, so that there will be no need to have this code in every widget.

```dart
final targetPlatform = Theme.of(context).platform;
final color = targetPlatform == TargetPlatform.android
        ? Theme.of(context).primaryColor
        : CupertinoTheme.of(context).primaryColor;
```

**Comment by feudadrien** [comment]
Great idea +1

**Comment by aqwert** [comment]
`PlatformApp` has a separate field for ios and android theming.

```
PlatformApp(
        title: 'Flutter Platform Widgets',
        android: (_) => new MaterialAppData(theme: themeData),
        ios: (_) => new CupertinoAppData(theme: cupertinoTheme),
        home: LandingPage(),
      ),
```

or is it more of a way to have your own widget pick up the base colors depending on the platform:

```
return MyWidget(
    color: PlatformTheme.of(context).primaryColor
);
```

These would only include properties that are shared between Theme and CupertinoTheme:
* brightness
* primaryColor
* scaffoldBackgroundColor

Others would need to get from Theme or CupertinoTheme itself

**Comment by VictorUvarov** [comment]
Guess it wouldn't be so useful since Cupertino has almost nothing in common.

**Comment by aqwert** [comment]
If you are on fluter 1.12 you could use extensions

```
extension ContextExt on BuildContext {
    Color get themePrimaryColor {
        final targetPlatform = Theme.of(this).platform;
        final color = targetPlatform == TargetPlatform.android
            ? Theme.of(this).primaryColor
            : CupertinoTheme.of(this).primaryColor;
    }
}

final color = context.themePrimaryColor;
```

**Comment by fredgrott** [comment]
hmm so okay per @aqwert I would set up extensionscontext and than se fontfamily, fontcolor, font style, primary colors, etc..  to dark and light themes than I would do it the same way just redefi9ne it in the dark and light themes.  Note, the new google_fonts plugin mentioned recently you need to convert to string for fontfamily
