### ISSUE TITLE
PlatformScaffold missing 'drawer'

### ISSUE THREAD

**Issue by dungnv2602** [aqwert/flutter_platform_widgets#96]
Don't see anywhere to put my drawer in.

**Comment by michaelwoods** [comment]
It's in the Data object: https://github.com/aqwert/flutter_platform_widgets/blob/master/lib/src/platform_scaffold.dart#L42

**Comment by dungnv2602** [comment]
So basically drawer only exist in MaterialScaffold? I'm feeling it doesn't make sense using this widget in any case which has a drawer? Any suggestion?

**Comment by aqwert** [comment]
That is the decision that the Flutter team has made. If you would like to submit an issue to flutter (https://github.com/flutter/flutter/issues) you could make a case for putting it on a Cupertino widget.

You can use the Material Scaffold with other Cupertino widgets but I am not sure what behavior or what it would look like.

**Comment by dungnv2602** [comment]
@aqwert Yeah sure, I'm gonna close this issue.
