### ISSUE TITLE
PlatformScaffold not working

### ISSUE THREAD

**Issue by Muki1992** [aqwert/flutter_platform_widgets#97]
Hey,

I just started using this library but somehow the app doesn't build an gives me this error:

Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:229:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../tools/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
      final obstruct = navigationBar.fullObstruction == null ||
                                     ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-0.20.2/lib/src/platform_scaffold.dart:230:25: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.
 - 'ObstructingPreferredSizeWidget' is from 'package:flutter/src/cupertino/page_scaffold.dart' ('../../tools/flutter/packages/flutter/lib/src/cupertino/page_scaffold.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'fullObstruction'.
          navigationBar.fullObstruction;
                        ^^^^^^^^^^^^^^^
Compiler failed on /Users/mustafagercek/Desktop/flutter_emmasapp/lib/main.dart
Error launching application on iPhone Xʀ.

  flutter_platform_widgets: ^0.20.2

**Comment by aqwert** [comment]
You are using a non-stable build of flutter. If you do `flutter channel` you will see what channel you are targeting.

I have a beta version that you will need to use instead: https://pub.dev/packages/flutter_platform_widgets/versions/0.20.3-beta.1

**Comment by Muki1992** [comment]
Thanks a lot!
