### ISSUE TITLE
help with web

### ISSUE THREAD

**Issue by shock-wave007** [aqwert/flutter_platform_widgets#99]
can u tell me how i can develop for ios android and web platform specific ui. as this library is not compatible with master/dev channels. any tips and tricks that i can use.

**Comment by aqwert** [comment]
Probably the best thing is to Fork this repo and reference (git reference) your version in your pubspec. If there are issues you can fix locally.

I cannot support Master as that changes to much and as this library needs to reference all the fields of a widget I would be spending every day checking if it was broken. The flutter dev channel releases a version almost everyday also so not much better there.

I do have a Beta branch that you could reference (and a beta version in pub.dev).

**Comment by shock-wave007** [comment]
thanks for your help. i understand  its a lot of efforts. 
**what language/technology u suggest for website development?**
as flutter for web is too unstable for production level. and i have developed application in java android. before i was interested in flutter

**Comment by aqwert** [comment]
As for web tech really depends on what you know now, what you are willing to learn and what you need to develop. There are a ton of ways to develop a website even ones where little coding is required.
